apiVersion: v1.1
resources:
  - name: gitfklogger
    type: GitRepo
    configuration:
      gitProvider: githubAccountGeoffwilliams
      path: declarativesystems/fklogger
pipelines:
  - name:   fklogger
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: "declarativesystems.jfrog.io/docker/docker-local/nodejs"
            tag: 0.0.0-4
            registry: artifactory
            sourceRepository: docker-local

    steps:
      - name: build
        type: declarativesystems/NpmBuild
        configuration:
          sourceArtifactory: artifactory
          sourceLocation: $res_gitfklogger_resourcePath
          repositoryName: npm
          buildCommand: make
          integrations:
            - name: artifactory
          inputResources:
            - name: gitfklogger
      - name: publish
        type: declarativesystems/NpmPublish
        configuration:
          sourceArtifactory: artifactory
          repositoryName: npm-local
          integrations:
            - name: artifactory
          inputSteps:
            - name: build