apiVersion: v1.1
resources:
  - name: gitfklogger
    type: GitRepo
    configuration:
      gitProvider: github_geoffwilliams               # Change to your integration
      path: declarativesystems/fklogger
pipelines:
  - name:   fklogger
    configuration:
      runtime:
        type: image
        image:
          # see https://www.jfrog.com/confluence/display/JFROG/Runtime+Images#RuntimeImages-Go

          # custom image
          # https://www.jfrog.com/confluence/display/JFROG/Choosing+your+Runtime+Image
          custom:
            name: "declarativesystems.jfrog.io/docker/docker-local/nodejs"
            tag: 0.0.0-3
            #options: "-e HOME=/root"
            registry: Artifactory            # if custom image is private, an integration is required for authentication
            sourceRepository: docker-local       # required if registry is Artifactory. e.g. docker-local

    steps:
      - name: build
        type: declarativesystems/NpmBuild
        configuration:
          sourceArtifactory: Artifactory
          repositoryName: npm
          buildCommand: make
          integrations:
            - name: Artifactory
          inputResources:
            - name: gitfklogger
      - name: publish
        type: declarativesystems/NpmPublish
        configuration:
          sourceArtifactory: Artifactory
          repositoryName: npm-local    # required, npm repository name on artifactory
          integrations:
            - name:        Artifactory
          inputSteps:
            - name:         build               # required
