apiVersion: v1.1
resources:
  - name: gitFkLogger
    type: GitRepo
    configuration:
      gitProvider: githubAccountGeoffwilliams
      path: declarativesystems/fklogger
  - name: npmEnvFkLogger
    type: declarativesystems/NpmEnv
    configuration:
      sourceArtifactory: artifactory
      repositoryName: npm

pipelines:
  - name: fkLogger
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: "declarativesystems.jfrog.io/docker-local/pipelines"
            tag: "0.6.1-26"
            registry: artifactory
            sourceRepository: docker-local

    steps:
      - name: npmBuildAndPublish
        type: Bash
        configuration:
          integrations:
            - name: artifactory
            - name: slack
          inputResources:
            - name: npmEnvFkLogger
            - name: gitFkLogger
        execution:
          onStart:
            - cd ${res_gitFkLogger_resourcePath}
            - make ci_notify_start
            - make test
            - yarn publish
          onFailure:
            - make ci_notify_failure
          onSuccess:
            - make ci_notify_complete
