apiVersion: v1.1
resources:
  - name: gitFkLogger
    type: GitRepo
    configuration:
      gitProvider: githubAccountGeoffwilliams
      path: declarativesystems/fklogger
pipelines:
  - name:   fklogger
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: "declarativesystems.jfrog.io/docker-local/pipelines"
            tag: "0.2.0-13"
            registry: artifactory
            sourceRepository: docker-local

    steps:
      - name: build
        type: declarativesystems/NpmBuild
        configuration:
          affinityGroup: fkloggerNpm
          sourceArtifactory: artifactory
          sourceLocation: $res_gitFkLogger_resourcePath
          repositoryName: npm
          buildCommand: make
          integrations:
            - name: artifactory
          inputResources:
            - name: gitFkLogger
        execution:
          onSuccess:
            - cd ${res_gitFkLogger_resourcePath}
            - add_pipeline_variables workdir=${res_gitFkLogger_resourcePath}
      - name: publish
        type: declarativesystems/NpmPublish
        configuration:
          affinityGroup: fkloggerNpm
          sourceArtifactory: artifactory
          repositoryName: npm-local
          integrations:
            - name: artifactory
          inputSteps:
            - name: build
        execution:
          onStart:
            - cd ${workdir}
